### ISSUE TITLE
No Copyright

### ISSUE THREAD

**Issue by abferm** [hsm5xw/Linux-Device-Driver-for-Character-LCD-Kernel-Level#1]
Hello, I was looking to fork your project to expand upon it and noticed that you have a license file, but no copyright information. I would like to credit you in my adaptation, but can not do that unless the information is available.

**Comment by hsm5xw** [comment]
See the beginning of each source file. Each one does have the Copyright
statement in the beginning.

The current license is Creative Commons
Attribution-NonCommercial-NoDerivatives 4.0 International Public License,
so no Derivative work is allowed or distributed at this point. Sorry.

**Comment by abferm** [comment]
That is unfortunate, as I see several ways this driver could be expanded to increase functionality and usability.
